services:
  backend:
    build:
      context: ./app/backend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 127.0.0.1:8000:8000
    expose:
      - 8000
    # Mount the backend directory into container for quick development
    #volumes:
    #  - ./app/backend:./home/user/app/backend

  frontend:
    build:
      context: ./app/frontend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 127.0.0.1:3006:3006
    expose:
      - 3006
    # Mount the frontend directory into container for quick development
    #volumes:
    #  - ./app/frontend:./app
