services:
  backend:
    build:
      context: ./app/backend/
      dockerfile: ./Dockerfile
    restart: always
    container_name: LLM-Secure-Deployment-Backend

  frontend:
    build:
      context: ./app/frontend/
      dockerfile: ./Dockerfile
    restart: always
    container_name: LLM-Secure-Deployment-Frontend
    ports:
      - 192.168.1.45:443:443 # Change the IP address here to the internal IP address of the host machine.
    expose:
      - 443

