services:
  backend:
    build:
      context: ./app/backend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 127.0.0.1:8000:8000
    expose:
      - 8000
    #volumes:
    #  - .:/backend

  frontend:
    build:
      context: ./app/frontend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 127.0.0.1:3006:3006
    expose:
      - 3006
    #volumes:
    #  - .:/frontend
